services:

  php:
    build:
      context: .
      dockerfile: php/Containerfile

    container_name: namaapp-php

    restart: unless-stopped

    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro

    environment:
      TZ: Asia/Jakarta

    depends_on:
      - redis

    networks:
      - namaapp-network


  nginx:
    image: docker.io/library/nginx:stable-alpine

    container_name: namaapp-nginx

    restart: unless-stopped

    depends_on:
      - php

    ports:
      - "8007:80" #sesuaikan portnya

    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - namaapp-network


  redis:
    image: docker.io/library/redis:7-alpine

    container_name: namaapp-redis

    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

    networks:
      - namaapp-network


networks:
  namaapp-network:


volumes:
  redis-data: