FROM docker.io/library/php:8.4-fpm

ENV DEBIAN_FRONTEND=noninteractive

# Install system package
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    zip \
    wget \
    ca-certificates \
    default-mysql-client \
    libzip-dev \
    libicu-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

# Configure GD
RUN docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg

# Install PHP Extension
RUN docker-php-ext-install -j$(nproc) \
    pdo_mysql \
    mysqli \
    mbstring \
    intl \
    zip \
    gd \
    exif \
    bcmath

# Install Composer
RUN curl -fsSL https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

WORKDIR /var/www/html

CMD ["php-fpm"]